export const DELETE_CARD = 'DELETE_CARD'
export const CHECK_TASK = 'CHECK_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const CHANGE_COLOR = 'CHANGE_COLOR'
export const ADD_CARD = 'ADD_CARD'
