export default {
  DELETE_CARD: 'DELETE_CARD',
  CHECK_TASK: 'CHECK_TASK',
  DELETE_TASK: 'DELETE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  ADD_TASK: 'ADD_TASK',
  UPDATE_TITLE: 'UPDATE_TITLE',
  CHANGE_COLOR: 'CHANGE_COLOR',
  ADD_CARD: 'ADD_CARD'
}
